"""empty message

Revision ID: 12f016ca61da
Revises: e303b3a3c348
Create Date: 2023-12-06 18:04:12.483715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f016ca61da'
down_revision: Union[str, None] = 'e303b3a3c348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_pivot', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('customer_pivot', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('customer_pivot', sa.Column('receipt_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customer_pivot', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'customer_pivot', 'receipts', ['receipt_id'], ['id'])
    op.create_foreign_key(None, 'customer_pivot', 'customer_info', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer_pivot', type_='foreignkey')
    op.drop_constraint(None, 'customer_pivot', type_='foreignkey')
    op.drop_constraint(None, 'customer_pivot', type_='foreignkey')
    op.drop_column('customer_pivot', 'receipt_id')
    op.drop_column('customer_pivot', 'customer_id')
    op.drop_column('customer_pivot', 'user_id')
    # ### end Alembic commands ###
