"""Added account table

Revision ID: 5c11b38d6d94
Revises: 72fb7301a163
Create Date: 2023-11-30 18:04:50.886106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c11b38d6d94'
down_revision: Union[str, None] = '72fb7301a163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_info_address'), 'customer_info', ['address'], unique=False)
    op.create_index(op.f('ix_customer_info_first_name'), 'customer_info', ['first_name'], unique=False)
    op.create_index(op.f('ix_customer_info_id'), 'customer_info', ['id'], unique=False)
    op.create_index(op.f('ix_customer_info_last_name'), 'customer_info', ['last_name'], unique=False)
    op.create_index(op.f('ix_customer_info_phone'), 'customer_info', ['phone'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_provided', sa.String(), nullable=True),
    sa.Column('parts_cost', sa.Float(), nullable=True),
    sa.Column('labor_cost', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_id'), 'receipts', ['id'], unique=False)
    op.create_index(op.f('ix_receipts_labor_cost'), 'receipts', ['labor_cost'], unique=False)
    op.create_index(op.f('ix_receipts_parts_cost'), 'receipts', ['parts_cost'], unique=False)
    op.create_index(op.f('ix_receipts_service_provided'), 'receipts', ['service_provided'], unique=False)
    op.create_index(op.f('ix_receipts_total'), 'receipts', ['total'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipts_total'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_service_provided'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_parts_cost'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_labor_cost'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_customer_info_phone'), table_name='customer_info')
    op.drop_index(op.f('ix_customer_info_last_name'), table_name='customer_info')
    op.drop_index(op.f('ix_customer_info_id'), table_name='customer_info')
    op.drop_index(op.f('ix_customer_info_first_name'), table_name='customer_info')
    op.drop_index(op.f('ix_customer_info_address'), table_name='customer_info')
    op.drop_table('customer_info')
    # ### end Alembic commands ###
