"""initial migration

Revision ID: e303b3a3c348
Revises: 5c11b38d6d94
Create Date: 2023-12-06 16:19:25.111325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e303b3a3c348'
down_revision: Union[str, None] = '5c11b38d6d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_pivot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_pivot_id'), 'customer_pivot', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_pivot_id'), table_name='customer_pivot')
    op.drop_table('customer_pivot')
    # ### end Alembic commands ###
